project_id = "hvciiodxmugcaqbjzvkn"

[functions.citadel-report]
verify_jwt = false

[functions.mentorship-escalation-notify]
verify_jwt = false

[functions.send-push]
verify_jwt = false

[functions.bps-checkpoint-notify]
verify_jwt = false

[functions.tpe-weekly-compliance]
verify_jwt = false

[functions.bps-daily-tracker-reminder]
verify_jwt = false

[functions.bps-daily-checkin]
verify_jwt = false

[functions.bps-checkpoint-due-reminder]
verify_jwt = false
