/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWeeklyReportRouteImport } from './routes/_authenticated/weekly-report'
import { Route as AuthenticatedReportRouteImport } from './routes/_authenticated/report'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCouncilReportsRouteImport } from './routes/_authenticated/council-reports'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAscentRouteRouteImport } from './routes/_authenticated/ascent/route'
import { Route as AuthenticatedPlaybooksIndexRouteImport } from './routes/_authenticated/playbooks/index'
import { Route as AuthenticatedAscentIndexRouteImport } from './routes/_authenticated/ascent/index'
import { Route as AuthenticatedPlaybooksSmbCalculatorRouteImport } from './routes/_authenticated/playbooks/smb-calculator'
import { Route as AuthenticatedPlaybooksPlanRouteImport } from './routes/_authenticated/playbooks/plan'
import { Route as AuthenticatedPlaybooksGlobalSmbEngineRouteImport } from './routes/_authenticated/playbooks/global-smb-engine'
import { Route as AuthenticatedAscentReportRouteImport } from './routes/_authenticated/ascent/report'
import { Route as AuthenticatedAscentCurriculumRouteImport } from './routes/_authenticated/ascent/curriculum'
import { Route as AuthenticatedAscentCouncilRouteImport } from './routes/_authenticated/ascent/council'
import { Route as AuthenticatedAscentCalendarRouteImport } from './routes/_authenticated/ascent/calendar'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWeeklyReportRoute =
  AuthenticatedWeeklyReportRouteImport.update({
    id: '/weekly-report',
    path: '/weekly-report',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportRoute = AuthenticatedReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCouncilReportsRoute =
  AuthenticatedCouncilReportsRouteImport.update({
    id: '/council-reports',
    path: '/council-reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAscentRouteRoute =
  AuthenticatedAscentRouteRouteImport.update({
    id: '/ascent',
    path: '/ascent',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlaybooksIndexRoute =
  AuthenticatedPlaybooksIndexRouteImport.update({
    id: '/playbooks/',
    path: '/playbooks/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAscentIndexRoute =
  AuthenticatedAscentIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAscentRouteRoute,
  } as any)
const AuthenticatedPlaybooksSmbCalculatorRoute =
  AuthenticatedPlaybooksSmbCalculatorRouteImport.update({
    id: '/playbooks/smb-calculator',
    path: '/playbooks/smb-calculator',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlaybooksPlanRoute =
  AuthenticatedPlaybooksPlanRouteImport.update({
    id: '/playbooks/plan',
    path: '/playbooks/plan',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlaybooksGlobalSmbEngineRoute =
  AuthenticatedPlaybooksGlobalSmbEngineRouteImport.update({
    id: '/playbooks/global-smb-engine',
    path: '/playbooks/global-smb-engine',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAscentReportRoute =
  AuthenticatedAscentReportRouteImport.update({
    id: '/report',
    path: '/report',
    getParentRoute: () => AuthenticatedAscentRouteRoute,
  } as any)
const AuthenticatedAscentCurriculumRoute =
  AuthenticatedAscentCurriculumRouteImport.update({
    id: '/curriculum',
    path: '/curriculum',
    getParentRoute: () => AuthenticatedAscentRouteRoute,
  } as any)
const AuthenticatedAscentCouncilRoute =
  AuthenticatedAscentCouncilRouteImport.update({
    id: '/council',
    path: '/council',
    getParentRoute: () => AuthenticatedAscentRouteRoute,
  } as any)
const AuthenticatedAscentCalendarRoute =
  AuthenticatedAscentCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedAscentRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/auth': typeof AuthRoute
  '/ascent': typeof AuthenticatedAscentRouteRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/council-reports': typeof AuthenticatedCouncilReportsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/report': typeof AuthenticatedReportRoute
  '/weekly-report': typeof AuthenticatedWeeklyReportRoute
  '/ascent/calendar': typeof AuthenticatedAscentCalendarRoute
  '/ascent/council': typeof AuthenticatedAscentCouncilRoute
  '/ascent/curriculum': typeof AuthenticatedAscentCurriculumRoute
  '/ascent/report': typeof AuthenticatedAscentReportRoute
  '/playbooks/global-smb-engine': typeof AuthenticatedPlaybooksGlobalSmbEngineRoute
  '/playbooks/plan': typeof AuthenticatedPlaybooksPlanRoute
  '/playbooks/smb-calculator': typeof AuthenticatedPlaybooksSmbCalculatorRoute
  '/ascent/': typeof AuthenticatedAscentIndexRoute
  '/playbooks/': typeof AuthenticatedPlaybooksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/council-reports': typeof AuthenticatedCouncilReportsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/report': typeof AuthenticatedReportRoute
  '/weekly-report': typeof AuthenticatedWeeklyReportRoute
  '/ascent/calendar': typeof AuthenticatedAscentCalendarRoute
  '/ascent/council': typeof AuthenticatedAscentCouncilRoute
  '/ascent/curriculum': typeof AuthenticatedAscentCurriculumRoute
  '/ascent/report': typeof AuthenticatedAscentReportRoute
  '/playbooks/global-smb-engine': typeof AuthenticatedPlaybooksGlobalSmbEngineRoute
  '/playbooks/plan': typeof AuthenticatedPlaybooksPlanRoute
  '/playbooks/smb-calculator': typeof AuthenticatedPlaybooksSmbCalculatorRoute
  '/ascent': typeof AuthenticatedAscentIndexRoute
  '/playbooks': typeof AuthenticatedPlaybooksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/auth': typeof AuthRoute
  '/_authenticated/ascent': typeof AuthenticatedAscentRouteRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/council-reports': typeof AuthenticatedCouncilReportsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/report': typeof AuthenticatedReportRoute
  '/_authenticated/weekly-report': typeof AuthenticatedWeeklyReportRoute
  '/_authenticated/ascent/calendar': typeof AuthenticatedAscentCalendarRoute
  '/_authenticated/ascent/council': typeof AuthenticatedAscentCouncilRoute
  '/_authenticated/ascent/curriculum': typeof AuthenticatedAscentCurriculumRoute
  '/_authenticated/ascent/report': typeof AuthenticatedAscentReportRoute
  '/_authenticated/playbooks/global-smb-engine': typeof AuthenticatedPlaybooksGlobalSmbEngineRoute
  '/_authenticated/playbooks/plan': typeof AuthenticatedPlaybooksPlanRoute
  '/_authenticated/playbooks/smb-calculator': typeof AuthenticatedPlaybooksSmbCalculatorRoute
  '/_authenticated/ascent/': typeof AuthenticatedAscentIndexRoute
  '/_authenticated/playbooks/': typeof AuthenticatedPlaybooksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/auth'
    | '/ascent'
    | '/admin'
    | '/calendar'
    | '/council-reports'
    | '/dashboard'
    | '/report'
    | '/weekly-report'
    | '/ascent/calendar'
    | '/ascent/council'
    | '/ascent/curriculum'
    | '/ascent/report'
    | '/playbooks/global-smb-engine'
    | '/playbooks/plan'
    | '/playbooks/smb-calculator'
    | '/ascent/'
    | '/playbooks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/auth'
    | '/admin'
    | '/calendar'
    | '/council-reports'
    | '/dashboard'
    | '/report'
    | '/weekly-report'
    | '/ascent/calendar'
    | '/ascent/council'
    | '/ascent/curriculum'
    | '/ascent/report'
    | '/playbooks/global-smb-engine'
    | '/playbooks/plan'
    | '/playbooks/smb-calculator'
    | '/ascent'
    | '/playbooks'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/accept-invite'
    | '/auth'
    | '/_authenticated/ascent'
    | '/_authenticated/admin'
    | '/_authenticated/calendar'
    | '/_authenticated/council-reports'
    | '/_authenticated/dashboard'
    | '/_authenticated/report'
    | '/_authenticated/weekly-report'
    | '/_authenticated/ascent/calendar'
    | '/_authenticated/ascent/council'
    | '/_authenticated/ascent/curriculum'
    | '/_authenticated/ascent/report'
    | '/_authenticated/playbooks/global-smb-engine'
    | '/_authenticated/playbooks/plan'
    | '/_authenticated/playbooks/smb-calculator'
    | '/_authenticated/ascent/'
    | '/_authenticated/playbooks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/weekly-report': {
      id: '/_authenticated/weekly-report'
      path: '/weekly-report'
      fullPath: '/weekly-report'
      preLoaderRoute: typeof AuthenticatedWeeklyReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report': {
      id: '/_authenticated/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof AuthenticatedReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/council-reports': {
      id: '/_authenticated/council-reports'
      path: '/council-reports'
      fullPath: '/council-reports'
      preLoaderRoute: typeof AuthenticatedCouncilReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ascent': {
      id: '/_authenticated/ascent'
      path: '/ascent'
      fullPath: '/ascent'
      preLoaderRoute: typeof AuthenticatedAscentRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/playbooks/': {
      id: '/_authenticated/playbooks/'
      path: '/playbooks'
      fullPath: '/playbooks/'
      preLoaderRoute: typeof AuthenticatedPlaybooksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ascent/': {
      id: '/_authenticated/ascent/'
      path: '/'
      fullPath: '/ascent/'
      preLoaderRoute: typeof AuthenticatedAscentIndexRouteImport
      parentRoute: typeof AuthenticatedAscentRouteRoute
    }
    '/_authenticated/playbooks/smb-calculator': {
      id: '/_authenticated/playbooks/smb-calculator'
      path: '/playbooks/smb-calculator'
      fullPath: '/playbooks/smb-calculator'
      preLoaderRoute: typeof AuthenticatedPlaybooksSmbCalculatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/playbooks/plan': {
      id: '/_authenticated/playbooks/plan'
      path: '/playbooks/plan'
      fullPath: '/playbooks/plan'
      preLoaderRoute: typeof AuthenticatedPlaybooksPlanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/playbooks/global-smb-engine': {
      id: '/_authenticated/playbooks/global-smb-engine'
      path: '/playbooks/global-smb-engine'
      fullPath: '/playbooks/global-smb-engine'
      preLoaderRoute: typeof AuthenticatedPlaybooksGlobalSmbEngineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ascent/report': {
      id: '/_authenticated/ascent/report'
      path: '/report'
      fullPath: '/ascent/report'
      preLoaderRoute: typeof AuthenticatedAscentReportRouteImport
      parentRoute: typeof AuthenticatedAscentRouteRoute
    }
    '/_authenticated/ascent/curriculum': {
      id: '/_authenticated/ascent/curriculum'
      path: '/curriculum'
      fullPath: '/ascent/curriculum'
      preLoaderRoute: typeof AuthenticatedAscentCurriculumRouteImport
      parentRoute: typeof AuthenticatedAscentRouteRoute
    }
    '/_authenticated/ascent/council': {
      id: '/_authenticated/ascent/council'
      path: '/council'
      fullPath: '/ascent/council'
      preLoaderRoute: typeof AuthenticatedAscentCouncilRouteImport
      parentRoute: typeof AuthenticatedAscentRouteRoute
    }
    '/_authenticated/ascent/calendar': {
      id: '/_authenticated/ascent/calendar'
      path: '/calendar'
      fullPath: '/ascent/calendar'
      preLoaderRoute: typeof AuthenticatedAscentCalendarRouteImport
      parentRoute: typeof AuthenticatedAscentRouteRoute
    }
  }
}

interface AuthenticatedAscentRouteRouteChildren {
  AuthenticatedAscentCalendarRoute: typeof AuthenticatedAscentCalendarRoute
  AuthenticatedAscentCouncilRoute: typeof AuthenticatedAscentCouncilRoute
  AuthenticatedAscentCurriculumRoute: typeof AuthenticatedAscentCurriculumRoute
  AuthenticatedAscentReportRoute: typeof AuthenticatedAscentReportRoute
  AuthenticatedAscentIndexRoute: typeof AuthenticatedAscentIndexRoute
}

const AuthenticatedAscentRouteRouteChildren: AuthenticatedAscentRouteRouteChildren =
  {
    AuthenticatedAscentCalendarRoute: AuthenticatedAscentCalendarRoute,
    AuthenticatedAscentCouncilRoute: AuthenticatedAscentCouncilRoute,
    AuthenticatedAscentCurriculumRoute: AuthenticatedAscentCurriculumRoute,
    AuthenticatedAscentReportRoute: AuthenticatedAscentReportRoute,
    AuthenticatedAscentIndexRoute: AuthenticatedAscentIndexRoute,
  }

const AuthenticatedAscentRouteRouteWithChildren =
  AuthenticatedAscentRouteRoute._addFileChildren(
    AuthenticatedAscentRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAscentRouteRoute: typeof AuthenticatedAscentRouteRouteWithChildren
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedCouncilReportsRoute: typeof AuthenticatedCouncilReportsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedReportRoute: typeof AuthenticatedReportRoute
  AuthenticatedWeeklyReportRoute: typeof AuthenticatedWeeklyReportRoute
  AuthenticatedPlaybooksGlobalSmbEngineRoute: typeof AuthenticatedPlaybooksGlobalSmbEngineRoute
  AuthenticatedPlaybooksPlanRoute: typeof AuthenticatedPlaybooksPlanRoute
  AuthenticatedPlaybooksSmbCalculatorRoute: typeof AuthenticatedPlaybooksSmbCalculatorRoute
  AuthenticatedPlaybooksIndexRoute: typeof AuthenticatedPlaybooksIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAscentRouteRoute: AuthenticatedAscentRouteRouteWithChildren,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedCouncilReportsRoute: AuthenticatedCouncilReportsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedReportRoute: AuthenticatedReportRoute,
  AuthenticatedWeeklyReportRoute: AuthenticatedWeeklyReportRoute,
  AuthenticatedPlaybooksGlobalSmbEngineRoute:
    AuthenticatedPlaybooksGlobalSmbEngineRoute,
  AuthenticatedPlaybooksPlanRoute: AuthenticatedPlaybooksPlanRoute,
  AuthenticatedPlaybooksSmbCalculatorRoute:
    AuthenticatedPlaybooksSmbCalculatorRoute,
  AuthenticatedPlaybooksIndexRoute: AuthenticatedPlaybooksIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
