/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWeeklyReportRouteImport } from './routes/_authenticated/weekly-report'
import { Route as AuthenticatedTpeRouteImport } from './routes/_authenticated/tpe'
import { Route as AuthenticatedReportRouteImport } from './routes/_authenticated/report'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedMentorshipRouteImport } from './routes/_authenticated/mentorship'
import { Route as AuthenticatedDfyRouteImport } from './routes/_authenticated/dfy'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCouncilReportsRouteImport } from './routes/_authenticated/council-reports'
import { Route as AuthenticatedCouncilPaymentsRouteImport } from './routes/_authenticated/council-payments'
import { Route as AuthenticatedCouncilMentorshipRouteImport } from './routes/_authenticated/council-mentorship'
import { Route as AuthenticatedCouncilEscalationsRouteImport } from './routes/_authenticated/council-escalations'
import { Route as AuthenticatedChoosePathRouteImport } from './routes/_authenticated/choose-path'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedBpsRouteImport } from './routes/_authenticated/bps'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedPlaybooksIndexRouteImport } from './routes/_authenticated/playbooks/index'
import { Route as AuthenticatedPlaybooksSmbCalculatorRouteImport } from './routes/_authenticated/playbooks/smb-calculator'
import { Route as AuthenticatedPlaybooksRevenueEngineRouteImport } from './routes/_authenticated/playbooks/revenue-engine'
import { Route as AuthenticatedPlaybooksPodcastProspectingRouteImport } from './routes/_authenticated/playbooks/podcast-prospecting'
import { Route as AuthenticatedPlaybooksPodcastCalculatorRouteImport } from './routes/_authenticated/playbooks/podcast-calculator'
import { Route as AuthenticatedPlaybooksPlanRouteImport } from './routes/_authenticated/playbooks/plan'
import { Route as AuthenticatedPlaybooksMinistrySystemsRouteImport } from './routes/_authenticated/playbooks/ministry-systems'
import { Route as AuthenticatedPlaybooksMinistryProspectingRouteImport } from './routes/_authenticated/playbooks/ministry-prospecting'
import { Route as AuthenticatedPlaybooksMinistryCalculatorRouteImport } from './routes/_authenticated/playbooks/ministry-calculator'
import { Route as AuthenticatedPlaybooksGlobalSmbEngineRouteImport } from './routes/_authenticated/playbooks/global-smb-engine'
import { Route as AuthenticatedPlaybooksEcommerceProspectingRouteImport } from './routes/_authenticated/playbooks/ecommerce-prospecting'
import { Route as AuthenticatedPlaybooksEcommerceCalculatorRouteImport } from './routes/_authenticated/playbooks/ecommerce-calculator'
import { Route as AuthenticatedPlaybooksCareProspectingRouteImport } from './routes/_authenticated/playbooks/care-prospecting'
import { Route as AuthenticatedPlaybooksCareCalculatorRouteImport } from './routes/_authenticated/playbooks/care-calculator'
import { Route as AuthenticatedPlaybooksCareBridgeRouteImport } from './routes/_authenticated/playbooks/care-bridge'
import { Route as AuthenticatedPlaybooksBroadcastEngineRouteImport } from './routes/_authenticated/playbooks/broadcast-engine'
import { Route as AuthenticatedPlaybooksAuthorityProspectingRouteImport } from './routes/_authenticated/playbooks/authority-prospecting'
import { Route as AuthenticatedPlaybooksAuthorityEngineRouteImport } from './routes/_authenticated/playbooks/authority-engine'
import { Route as AuthenticatedPlaybooksAuthorityCalculatorRouteImport } from './routes/_authenticated/playbooks/authority-calculator'
import { Route as AuthenticatedPlaybooksAscentTargetingRouteImport } from './routes/_authenticated/playbooks/ascent-targeting'
import { Route as AuthenticatedPlaybooksAscentMachineRouteImport } from './routes/_authenticated/playbooks/ascent-machine'
import { Route as AuthenticatedPlaybooksAscentCalculatorRouteImport } from './routes/_authenticated/playbooks/ascent-calculator'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWeeklyReportRoute =
  AuthenticatedWeeklyReportRouteImport.update({
    id: '/weekly-report',
    path: '/weekly-report',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTpeRoute = AuthenticatedTpeRouteImport.update({
  id: '/tpe',
  path: '/tpe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportRoute = AuthenticatedReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMentorshipRoute = AuthenticatedMentorshipRouteImport.update({
  id: '/mentorship',
  path: '/mentorship',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDfyRoute = AuthenticatedDfyRouteImport.update({
  id: '/dfy',
  path: '/dfy',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCouncilReportsRoute =
  AuthenticatedCouncilReportsRouteImport.update({
    id: '/council-reports',
    path: '/council-reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCouncilPaymentsRoute =
  AuthenticatedCouncilPaymentsRouteImport.update({
    id: '/council-payments',
    path: '/council-payments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCouncilMentorshipRoute =
  AuthenticatedCouncilMentorshipRouteImport.update({
    id: '/council-mentorship',
    path: '/council-mentorship',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCouncilEscalationsRoute =
  AuthenticatedCouncilEscalationsRouteImport.update({
    id: '/council-escalations',
    path: '/council-escalations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChoosePathRoute = AuthenticatedChoosePathRouteImport.update({
  id: '/choose-path',
  path: '/choose-path',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBpsRoute = AuthenticatedBpsRouteImport.update({
  id: '/bps',
  path: '/bps',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlaybooksIndexRoute =
  AuthenticatedPlaybooksIndexRouteImport.update({
    id: '/playbooks/',
    path: '/playbooks/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlaybooksSmbCalculatorRoute =
  AuthenticatedPlaybooksSmbCalculatorRouteImport.update({
    id: '/playbooks/smb-calculator',
    path: '/playbooks/smb-calculator',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlaybooksRevenueEngineRoute =
  AuthenticatedPlaybooksRevenueEngineRouteImport.update({
    id: '/playbooks/revenue-engine',
    path: '/playbooks/revenue-engine',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlaybooksPodcastProspectingRoute =
  AuthenticatedPlaybooksPodcastProspectingRouteImport.update({
    id: '/playbooks/podcast-prospecting',
    path: '/playbooks/podcast-prospecting',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlaybooksPodcastCalculatorRoute =
  AuthenticatedPlaybooksPodcastCalculatorRouteImport.update({
    id: '/playbooks/podcast-calculator',
    path: '/playbooks/podcast-calculator',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlaybooksPlanRoute =
  AuthenticatedPlaybooksPlanRouteImport.update({
    id: '/playbooks/plan',
    path: '/playbooks/plan',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlaybooksMinistrySystemsRoute =
  AuthenticatedPlaybooksMinistrySystemsRouteImport.update({
    id: '/playbooks/ministry-systems',
    path: '/playbooks/ministry-systems',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlaybooksMinistryProspectingRoute =
  AuthenticatedPlaybooksMinistryProspectingRouteImport.update({
    id: '/playbooks/ministry-prospecting',
    path: '/playbooks/ministry-prospecting',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlaybooksMinistryCalculatorRoute =
  AuthenticatedPlaybooksMinistryCalculatorRouteImport.update({
    id: '/playbooks/ministry-calculator',
    path: '/playbooks/ministry-calculator',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlaybooksGlobalSmbEngineRoute =
  AuthenticatedPlaybooksGlobalSmbEngineRouteImport.update({
    id: '/playbooks/global-smb-engine',
    path: '/playbooks/global-smb-engine',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlaybooksEcommerceProspectingRoute =
  AuthenticatedPlaybooksEcommerceProspectingRouteImport.update({
    id: '/playbooks/ecommerce-prospecting',
    path: '/playbooks/ecommerce-prospecting',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlaybooksEcommerceCalculatorRoute =
  AuthenticatedPlaybooksEcommerceCalculatorRouteImport.update({
    id: '/playbooks/ecommerce-calculator',
    path: '/playbooks/ecommerce-calculator',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlaybooksCareProspectingRoute =
  AuthenticatedPlaybooksCareProspectingRouteImport.update({
    id: '/playbooks/care-prospecting',
    path: '/playbooks/care-prospecting',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlaybooksCareCalculatorRoute =
  AuthenticatedPlaybooksCareCalculatorRouteImport.update({
    id: '/playbooks/care-calculator',
    path: '/playbooks/care-calculator',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlaybooksCareBridgeRoute =
  AuthenticatedPlaybooksCareBridgeRouteImport.update({
    id: '/playbooks/care-bridge',
    path: '/playbooks/care-bridge',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlaybooksBroadcastEngineRoute =
  AuthenticatedPlaybooksBroadcastEngineRouteImport.update({
    id: '/playbooks/broadcast-engine',
    path: '/playbooks/broadcast-engine',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlaybooksAuthorityProspectingRoute =
  AuthenticatedPlaybooksAuthorityProspectingRouteImport.update({
    id: '/playbooks/authority-prospecting',
    path: '/playbooks/authority-prospecting',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlaybooksAuthorityEngineRoute =
  AuthenticatedPlaybooksAuthorityEngineRouteImport.update({
    id: '/playbooks/authority-engine',
    path: '/playbooks/authority-engine',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlaybooksAuthorityCalculatorRoute =
  AuthenticatedPlaybooksAuthorityCalculatorRouteImport.update({
    id: '/playbooks/authority-calculator',
    path: '/playbooks/authority-calculator',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlaybooksAscentTargetingRoute =
  AuthenticatedPlaybooksAscentTargetingRouteImport.update({
    id: '/playbooks/ascent-targeting',
    path: '/playbooks/ascent-targeting',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlaybooksAscentMachineRoute =
  AuthenticatedPlaybooksAscentMachineRouteImport.update({
    id: '/playbooks/ascent-machine',
    path: '/playbooks/ascent-machine',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlaybooksAscentCalculatorRoute =
  AuthenticatedPlaybooksAscentCalculatorRouteImport.update({
    id: '/playbooks/ascent-calculator',
    path: '/playbooks/ascent-calculator',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/bps': typeof AuthenticatedBpsRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/choose-path': typeof AuthenticatedChoosePathRoute
  '/council-escalations': typeof AuthenticatedCouncilEscalationsRoute
  '/council-mentorship': typeof AuthenticatedCouncilMentorshipRoute
  '/council-payments': typeof AuthenticatedCouncilPaymentsRoute
  '/council-reports': typeof AuthenticatedCouncilReportsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dfy': typeof AuthenticatedDfyRoute
  '/mentorship': typeof AuthenticatedMentorshipRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/report': typeof AuthenticatedReportRoute
  '/tpe': typeof AuthenticatedTpeRoute
  '/weekly-report': typeof AuthenticatedWeeklyReportRoute
  '/playbooks/ascent-calculator': typeof AuthenticatedPlaybooksAscentCalculatorRoute
  '/playbooks/ascent-machine': typeof AuthenticatedPlaybooksAscentMachineRoute
  '/playbooks/ascent-targeting': typeof AuthenticatedPlaybooksAscentTargetingRoute
  '/playbooks/authority-calculator': typeof AuthenticatedPlaybooksAuthorityCalculatorRoute
  '/playbooks/authority-engine': typeof AuthenticatedPlaybooksAuthorityEngineRoute
  '/playbooks/authority-prospecting': typeof AuthenticatedPlaybooksAuthorityProspectingRoute
  '/playbooks/broadcast-engine': typeof AuthenticatedPlaybooksBroadcastEngineRoute
  '/playbooks/care-bridge': typeof AuthenticatedPlaybooksCareBridgeRoute
  '/playbooks/care-calculator': typeof AuthenticatedPlaybooksCareCalculatorRoute
  '/playbooks/care-prospecting': typeof AuthenticatedPlaybooksCareProspectingRoute
  '/playbooks/ecommerce-calculator': typeof AuthenticatedPlaybooksEcommerceCalculatorRoute
  '/playbooks/ecommerce-prospecting': typeof AuthenticatedPlaybooksEcommerceProspectingRoute
  '/playbooks/global-smb-engine': typeof AuthenticatedPlaybooksGlobalSmbEngineRoute
  '/playbooks/ministry-calculator': typeof AuthenticatedPlaybooksMinistryCalculatorRoute
  '/playbooks/ministry-prospecting': typeof AuthenticatedPlaybooksMinistryProspectingRoute
  '/playbooks/ministry-systems': typeof AuthenticatedPlaybooksMinistrySystemsRoute
  '/playbooks/plan': typeof AuthenticatedPlaybooksPlanRoute
  '/playbooks/podcast-calculator': typeof AuthenticatedPlaybooksPodcastCalculatorRoute
  '/playbooks/podcast-prospecting': typeof AuthenticatedPlaybooksPodcastProspectingRoute
  '/playbooks/revenue-engine': typeof AuthenticatedPlaybooksRevenueEngineRoute
  '/playbooks/smb-calculator': typeof AuthenticatedPlaybooksSmbCalculatorRoute
  '/playbooks/': typeof AuthenticatedPlaybooksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/bps': typeof AuthenticatedBpsRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/choose-path': typeof AuthenticatedChoosePathRoute
  '/council-escalations': typeof AuthenticatedCouncilEscalationsRoute
  '/council-mentorship': typeof AuthenticatedCouncilMentorshipRoute
  '/council-payments': typeof AuthenticatedCouncilPaymentsRoute
  '/council-reports': typeof AuthenticatedCouncilReportsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dfy': typeof AuthenticatedDfyRoute
  '/mentorship': typeof AuthenticatedMentorshipRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/report': typeof AuthenticatedReportRoute
  '/tpe': typeof AuthenticatedTpeRoute
  '/weekly-report': typeof AuthenticatedWeeklyReportRoute
  '/playbooks/ascent-calculator': typeof AuthenticatedPlaybooksAscentCalculatorRoute
  '/playbooks/ascent-machine': typeof AuthenticatedPlaybooksAscentMachineRoute
  '/playbooks/ascent-targeting': typeof AuthenticatedPlaybooksAscentTargetingRoute
  '/playbooks/authority-calculator': typeof AuthenticatedPlaybooksAuthorityCalculatorRoute
  '/playbooks/authority-engine': typeof AuthenticatedPlaybooksAuthorityEngineRoute
  '/playbooks/authority-prospecting': typeof AuthenticatedPlaybooksAuthorityProspectingRoute
  '/playbooks/broadcast-engine': typeof AuthenticatedPlaybooksBroadcastEngineRoute
  '/playbooks/care-bridge': typeof AuthenticatedPlaybooksCareBridgeRoute
  '/playbooks/care-calculator': typeof AuthenticatedPlaybooksCareCalculatorRoute
  '/playbooks/care-prospecting': typeof AuthenticatedPlaybooksCareProspectingRoute
  '/playbooks/ecommerce-calculator': typeof AuthenticatedPlaybooksEcommerceCalculatorRoute
  '/playbooks/ecommerce-prospecting': typeof AuthenticatedPlaybooksEcommerceProspectingRoute
  '/playbooks/global-smb-engine': typeof AuthenticatedPlaybooksGlobalSmbEngineRoute
  '/playbooks/ministry-calculator': typeof AuthenticatedPlaybooksMinistryCalculatorRoute
  '/playbooks/ministry-prospecting': typeof AuthenticatedPlaybooksMinistryProspectingRoute
  '/playbooks/ministry-systems': typeof AuthenticatedPlaybooksMinistrySystemsRoute
  '/playbooks/plan': typeof AuthenticatedPlaybooksPlanRoute
  '/playbooks/podcast-calculator': typeof AuthenticatedPlaybooksPodcastCalculatorRoute
  '/playbooks/podcast-prospecting': typeof AuthenticatedPlaybooksPodcastProspectingRoute
  '/playbooks/revenue-engine': typeof AuthenticatedPlaybooksRevenueEngineRoute
  '/playbooks/smb-calculator': typeof AuthenticatedPlaybooksSmbCalculatorRoute
  '/playbooks': typeof AuthenticatedPlaybooksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/bps': typeof AuthenticatedBpsRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/choose-path': typeof AuthenticatedChoosePathRoute
  '/_authenticated/council-escalations': typeof AuthenticatedCouncilEscalationsRoute
  '/_authenticated/council-mentorship': typeof AuthenticatedCouncilMentorshipRoute
  '/_authenticated/council-payments': typeof AuthenticatedCouncilPaymentsRoute
  '/_authenticated/council-reports': typeof AuthenticatedCouncilReportsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/dfy': typeof AuthenticatedDfyRoute
  '/_authenticated/mentorship': typeof AuthenticatedMentorshipRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/report': typeof AuthenticatedReportRoute
  '/_authenticated/tpe': typeof AuthenticatedTpeRoute
  '/_authenticated/weekly-report': typeof AuthenticatedWeeklyReportRoute
  '/_authenticated/playbooks/ascent-calculator': typeof AuthenticatedPlaybooksAscentCalculatorRoute
  '/_authenticated/playbooks/ascent-machine': typeof AuthenticatedPlaybooksAscentMachineRoute
  '/_authenticated/playbooks/ascent-targeting': typeof AuthenticatedPlaybooksAscentTargetingRoute
  '/_authenticated/playbooks/authority-calculator': typeof AuthenticatedPlaybooksAuthorityCalculatorRoute
  '/_authenticated/playbooks/authority-engine': typeof AuthenticatedPlaybooksAuthorityEngineRoute
  '/_authenticated/playbooks/authority-prospecting': typeof AuthenticatedPlaybooksAuthorityProspectingRoute
  '/_authenticated/playbooks/broadcast-engine': typeof AuthenticatedPlaybooksBroadcastEngineRoute
  '/_authenticated/playbooks/care-bridge': typeof AuthenticatedPlaybooksCareBridgeRoute
  '/_authenticated/playbooks/care-calculator': typeof AuthenticatedPlaybooksCareCalculatorRoute
  '/_authenticated/playbooks/care-prospecting': typeof AuthenticatedPlaybooksCareProspectingRoute
  '/_authenticated/playbooks/ecommerce-calculator': typeof AuthenticatedPlaybooksEcommerceCalculatorRoute
  '/_authenticated/playbooks/ecommerce-prospecting': typeof AuthenticatedPlaybooksEcommerceProspectingRoute
  '/_authenticated/playbooks/global-smb-engine': typeof AuthenticatedPlaybooksGlobalSmbEngineRoute
  '/_authenticated/playbooks/ministry-calculator': typeof AuthenticatedPlaybooksMinistryCalculatorRoute
  '/_authenticated/playbooks/ministry-prospecting': typeof AuthenticatedPlaybooksMinistryProspectingRoute
  '/_authenticated/playbooks/ministry-systems': typeof AuthenticatedPlaybooksMinistrySystemsRoute
  '/_authenticated/playbooks/plan': typeof AuthenticatedPlaybooksPlanRoute
  '/_authenticated/playbooks/podcast-calculator': typeof AuthenticatedPlaybooksPodcastCalculatorRoute
  '/_authenticated/playbooks/podcast-prospecting': typeof AuthenticatedPlaybooksPodcastProspectingRoute
  '/_authenticated/playbooks/revenue-engine': typeof AuthenticatedPlaybooksRevenueEngineRoute
  '/_authenticated/playbooks/smb-calculator': typeof AuthenticatedPlaybooksSmbCalculatorRoute
  '/_authenticated/playbooks/': typeof AuthenticatedPlaybooksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/auth'
    | '/admin'
    | '/bps'
    | '/calendar'
    | '/choose-path'
    | '/council-escalations'
    | '/council-mentorship'
    | '/council-payments'
    | '/council-reports'
    | '/dashboard'
    | '/dfy'
    | '/mentorship'
    | '/messages'
    | '/payments'
    | '/profile'
    | '/report'
    | '/tpe'
    | '/weekly-report'
    | '/playbooks/ascent-calculator'
    | '/playbooks/ascent-machine'
    | '/playbooks/ascent-targeting'
    | '/playbooks/authority-calculator'
    | '/playbooks/authority-engine'
    | '/playbooks/authority-prospecting'
    | '/playbooks/broadcast-engine'
    | '/playbooks/care-bridge'
    | '/playbooks/care-calculator'
    | '/playbooks/care-prospecting'
    | '/playbooks/ecommerce-calculator'
    | '/playbooks/ecommerce-prospecting'
    | '/playbooks/global-smb-engine'
    | '/playbooks/ministry-calculator'
    | '/playbooks/ministry-prospecting'
    | '/playbooks/ministry-systems'
    | '/playbooks/plan'
    | '/playbooks/podcast-calculator'
    | '/playbooks/podcast-prospecting'
    | '/playbooks/revenue-engine'
    | '/playbooks/smb-calculator'
    | '/playbooks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/auth'
    | '/admin'
    | '/bps'
    | '/calendar'
    | '/choose-path'
    | '/council-escalations'
    | '/council-mentorship'
    | '/council-payments'
    | '/council-reports'
    | '/dashboard'
    | '/dfy'
    | '/mentorship'
    | '/messages'
    | '/payments'
    | '/profile'
    | '/report'
    | '/tpe'
    | '/weekly-report'
    | '/playbooks/ascent-calculator'
    | '/playbooks/ascent-machine'
    | '/playbooks/ascent-targeting'
    | '/playbooks/authority-calculator'
    | '/playbooks/authority-engine'
    | '/playbooks/authority-prospecting'
    | '/playbooks/broadcast-engine'
    | '/playbooks/care-bridge'
    | '/playbooks/care-calculator'
    | '/playbooks/care-prospecting'
    | '/playbooks/ecommerce-calculator'
    | '/playbooks/ecommerce-prospecting'
    | '/playbooks/global-smb-engine'
    | '/playbooks/ministry-calculator'
    | '/playbooks/ministry-prospecting'
    | '/playbooks/ministry-systems'
    | '/playbooks/plan'
    | '/playbooks/podcast-calculator'
    | '/playbooks/podcast-prospecting'
    | '/playbooks/revenue-engine'
    | '/playbooks/smb-calculator'
    | '/playbooks'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/accept-invite'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/bps'
    | '/_authenticated/calendar'
    | '/_authenticated/choose-path'
    | '/_authenticated/council-escalations'
    | '/_authenticated/council-mentorship'
    | '/_authenticated/council-payments'
    | '/_authenticated/council-reports'
    | '/_authenticated/dashboard'
    | '/_authenticated/dfy'
    | '/_authenticated/mentorship'
    | '/_authenticated/messages'
    | '/_authenticated/payments'
    | '/_authenticated/profile'
    | '/_authenticated/report'
    | '/_authenticated/tpe'
    | '/_authenticated/weekly-report'
    | '/_authenticated/playbooks/ascent-calculator'
    | '/_authenticated/playbooks/ascent-machine'
    | '/_authenticated/playbooks/ascent-targeting'
    | '/_authenticated/playbooks/authority-calculator'
    | '/_authenticated/playbooks/authority-engine'
    | '/_authenticated/playbooks/authority-prospecting'
    | '/_authenticated/playbooks/broadcast-engine'
    | '/_authenticated/playbooks/care-bridge'
    | '/_authenticated/playbooks/care-calculator'
    | '/_authenticated/playbooks/care-prospecting'
    | '/_authenticated/playbooks/ecommerce-calculator'
    | '/_authenticated/playbooks/ecommerce-prospecting'
    | '/_authenticated/playbooks/global-smb-engine'
    | '/_authenticated/playbooks/ministry-calculator'
    | '/_authenticated/playbooks/ministry-prospecting'
    | '/_authenticated/playbooks/ministry-systems'
    | '/_authenticated/playbooks/plan'
    | '/_authenticated/playbooks/podcast-calculator'
    | '/_authenticated/playbooks/podcast-prospecting'
    | '/_authenticated/playbooks/revenue-engine'
    | '/_authenticated/playbooks/smb-calculator'
    | '/_authenticated/playbooks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/weekly-report': {
      id: '/_authenticated/weekly-report'
      path: '/weekly-report'
      fullPath: '/weekly-report'
      preLoaderRoute: typeof AuthenticatedWeeklyReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tpe': {
      id: '/_authenticated/tpe'
      path: '/tpe'
      fullPath: '/tpe'
      preLoaderRoute: typeof AuthenticatedTpeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report': {
      id: '/_authenticated/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof AuthenticatedReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mentorship': {
      id: '/_authenticated/mentorship'
      path: '/mentorship'
      fullPath: '/mentorship'
      preLoaderRoute: typeof AuthenticatedMentorshipRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dfy': {
      id: '/_authenticated/dfy'
      path: '/dfy'
      fullPath: '/dfy'
      preLoaderRoute: typeof AuthenticatedDfyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/council-reports': {
      id: '/_authenticated/council-reports'
      path: '/council-reports'
      fullPath: '/council-reports'
      preLoaderRoute: typeof AuthenticatedCouncilReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/council-payments': {
      id: '/_authenticated/council-payments'
      path: '/council-payments'
      fullPath: '/council-payments'
      preLoaderRoute: typeof AuthenticatedCouncilPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/council-mentorship': {
      id: '/_authenticated/council-mentorship'
      path: '/council-mentorship'
      fullPath: '/council-mentorship'
      preLoaderRoute: typeof AuthenticatedCouncilMentorshipRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/council-escalations': {
      id: '/_authenticated/council-escalations'
      path: '/council-escalations'
      fullPath: '/council-escalations'
      preLoaderRoute: typeof AuthenticatedCouncilEscalationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/choose-path': {
      id: '/_authenticated/choose-path'
      path: '/choose-path'
      fullPath: '/choose-path'
      preLoaderRoute: typeof AuthenticatedChoosePathRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bps': {
      id: '/_authenticated/bps'
      path: '/bps'
      fullPath: '/bps'
      preLoaderRoute: typeof AuthenticatedBpsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/playbooks/': {
      id: '/_authenticated/playbooks/'
      path: '/playbooks'
      fullPath: '/playbooks/'
      preLoaderRoute: typeof AuthenticatedPlaybooksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/playbooks/smb-calculator': {
      id: '/_authenticated/playbooks/smb-calculator'
      path: '/playbooks/smb-calculator'
      fullPath: '/playbooks/smb-calculator'
      preLoaderRoute: typeof AuthenticatedPlaybooksSmbCalculatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/playbooks/revenue-engine': {
      id: '/_authenticated/playbooks/revenue-engine'
      path: '/playbooks/revenue-engine'
      fullPath: '/playbooks/revenue-engine'
      preLoaderRoute: typeof AuthenticatedPlaybooksRevenueEngineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/playbooks/podcast-prospecting': {
      id: '/_authenticated/playbooks/podcast-prospecting'
      path: '/playbooks/podcast-prospecting'
      fullPath: '/playbooks/podcast-prospecting'
      preLoaderRoute: typeof AuthenticatedPlaybooksPodcastProspectingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/playbooks/podcast-calculator': {
      id: '/_authenticated/playbooks/podcast-calculator'
      path: '/playbooks/podcast-calculator'
      fullPath: '/playbooks/podcast-calculator'
      preLoaderRoute: typeof AuthenticatedPlaybooksPodcastCalculatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/playbooks/plan': {
      id: '/_authenticated/playbooks/plan'
      path: '/playbooks/plan'
      fullPath: '/playbooks/plan'
      preLoaderRoute: typeof AuthenticatedPlaybooksPlanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/playbooks/ministry-systems': {
      id: '/_authenticated/playbooks/ministry-systems'
      path: '/playbooks/ministry-systems'
      fullPath: '/playbooks/ministry-systems'
      preLoaderRoute: typeof AuthenticatedPlaybooksMinistrySystemsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/playbooks/ministry-prospecting': {
      id: '/_authenticated/playbooks/ministry-prospecting'
      path: '/playbooks/ministry-prospecting'
      fullPath: '/playbooks/ministry-prospecting'
      preLoaderRoute: typeof AuthenticatedPlaybooksMinistryProspectingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/playbooks/ministry-calculator': {
      id: '/_authenticated/playbooks/ministry-calculator'
      path: '/playbooks/ministry-calculator'
      fullPath: '/playbooks/ministry-calculator'
      preLoaderRoute: typeof AuthenticatedPlaybooksMinistryCalculatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/playbooks/global-smb-engine': {
      id: '/_authenticated/playbooks/global-smb-engine'
      path: '/playbooks/global-smb-engine'
      fullPath: '/playbooks/global-smb-engine'
      preLoaderRoute: typeof AuthenticatedPlaybooksGlobalSmbEngineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/playbooks/ecommerce-prospecting': {
      id: '/_authenticated/playbooks/ecommerce-prospecting'
      path: '/playbooks/ecommerce-prospecting'
      fullPath: '/playbooks/ecommerce-prospecting'
      preLoaderRoute: typeof AuthenticatedPlaybooksEcommerceProspectingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/playbooks/ecommerce-calculator': {
      id: '/_authenticated/playbooks/ecommerce-calculator'
      path: '/playbooks/ecommerce-calculator'
      fullPath: '/playbooks/ecommerce-calculator'
      preLoaderRoute: typeof AuthenticatedPlaybooksEcommerceCalculatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/playbooks/care-prospecting': {
      id: '/_authenticated/playbooks/care-prospecting'
      path: '/playbooks/care-prospecting'
      fullPath: '/playbooks/care-prospecting'
      preLoaderRoute: typeof AuthenticatedPlaybooksCareProspectingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/playbooks/care-calculator': {
      id: '/_authenticated/playbooks/care-calculator'
      path: '/playbooks/care-calculator'
      fullPath: '/playbooks/care-calculator'
      preLoaderRoute: typeof AuthenticatedPlaybooksCareCalculatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/playbooks/care-bridge': {
      id: '/_authenticated/playbooks/care-bridge'
      path: '/playbooks/care-bridge'
      fullPath: '/playbooks/care-bridge'
      preLoaderRoute: typeof AuthenticatedPlaybooksCareBridgeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/playbooks/broadcast-engine': {
      id: '/_authenticated/playbooks/broadcast-engine'
      path: '/playbooks/broadcast-engine'
      fullPath: '/playbooks/broadcast-engine'
      preLoaderRoute: typeof AuthenticatedPlaybooksBroadcastEngineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/playbooks/authority-prospecting': {
      id: '/_authenticated/playbooks/authority-prospecting'
      path: '/playbooks/authority-prospecting'
      fullPath: '/playbooks/authority-prospecting'
      preLoaderRoute: typeof AuthenticatedPlaybooksAuthorityProspectingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/playbooks/authority-engine': {
      id: '/_authenticated/playbooks/authority-engine'
      path: '/playbooks/authority-engine'
      fullPath: '/playbooks/authority-engine'
      preLoaderRoute: typeof AuthenticatedPlaybooksAuthorityEngineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/playbooks/authority-calculator': {
      id: '/_authenticated/playbooks/authority-calculator'
      path: '/playbooks/authority-calculator'
      fullPath: '/playbooks/authority-calculator'
      preLoaderRoute: typeof AuthenticatedPlaybooksAuthorityCalculatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/playbooks/ascent-targeting': {
      id: '/_authenticated/playbooks/ascent-targeting'
      path: '/playbooks/ascent-targeting'
      fullPath: '/playbooks/ascent-targeting'
      preLoaderRoute: typeof AuthenticatedPlaybooksAscentTargetingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/playbooks/ascent-machine': {
      id: '/_authenticated/playbooks/ascent-machine'
      path: '/playbooks/ascent-machine'
      fullPath: '/playbooks/ascent-machine'
      preLoaderRoute: typeof AuthenticatedPlaybooksAscentMachineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/playbooks/ascent-calculator': {
      id: '/_authenticated/playbooks/ascent-calculator'
      path: '/playbooks/ascent-calculator'
      fullPath: '/playbooks/ascent-calculator'
      preLoaderRoute: typeof AuthenticatedPlaybooksAscentCalculatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBpsRoute: typeof AuthenticatedBpsRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedChoosePathRoute: typeof AuthenticatedChoosePathRoute
  AuthenticatedCouncilEscalationsRoute: typeof AuthenticatedCouncilEscalationsRoute
  AuthenticatedCouncilMentorshipRoute: typeof AuthenticatedCouncilMentorshipRoute
  AuthenticatedCouncilPaymentsRoute: typeof AuthenticatedCouncilPaymentsRoute
  AuthenticatedCouncilReportsRoute: typeof AuthenticatedCouncilReportsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDfyRoute: typeof AuthenticatedDfyRoute
  AuthenticatedMentorshipRoute: typeof AuthenticatedMentorshipRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReportRoute: typeof AuthenticatedReportRoute
  AuthenticatedTpeRoute: typeof AuthenticatedTpeRoute
  AuthenticatedWeeklyReportRoute: typeof AuthenticatedWeeklyReportRoute
  AuthenticatedPlaybooksAscentCalculatorRoute: typeof AuthenticatedPlaybooksAscentCalculatorRoute
  AuthenticatedPlaybooksAscentMachineRoute: typeof AuthenticatedPlaybooksAscentMachineRoute
  AuthenticatedPlaybooksAscentTargetingRoute: typeof AuthenticatedPlaybooksAscentTargetingRoute
  AuthenticatedPlaybooksAuthorityCalculatorRoute: typeof AuthenticatedPlaybooksAuthorityCalculatorRoute
  AuthenticatedPlaybooksAuthorityEngineRoute: typeof AuthenticatedPlaybooksAuthorityEngineRoute
  AuthenticatedPlaybooksAuthorityProspectingRoute: typeof AuthenticatedPlaybooksAuthorityProspectingRoute
  AuthenticatedPlaybooksBroadcastEngineRoute: typeof AuthenticatedPlaybooksBroadcastEngineRoute
  AuthenticatedPlaybooksCareBridgeRoute: typeof AuthenticatedPlaybooksCareBridgeRoute
  AuthenticatedPlaybooksCareCalculatorRoute: typeof AuthenticatedPlaybooksCareCalculatorRoute
  AuthenticatedPlaybooksCareProspectingRoute: typeof AuthenticatedPlaybooksCareProspectingRoute
  AuthenticatedPlaybooksEcommerceCalculatorRoute: typeof AuthenticatedPlaybooksEcommerceCalculatorRoute
  AuthenticatedPlaybooksEcommerceProspectingRoute: typeof AuthenticatedPlaybooksEcommerceProspectingRoute
  AuthenticatedPlaybooksGlobalSmbEngineRoute: typeof AuthenticatedPlaybooksGlobalSmbEngineRoute
  AuthenticatedPlaybooksMinistryCalculatorRoute: typeof AuthenticatedPlaybooksMinistryCalculatorRoute
  AuthenticatedPlaybooksMinistryProspectingRoute: typeof AuthenticatedPlaybooksMinistryProspectingRoute
  AuthenticatedPlaybooksMinistrySystemsRoute: typeof AuthenticatedPlaybooksMinistrySystemsRoute
  AuthenticatedPlaybooksPlanRoute: typeof AuthenticatedPlaybooksPlanRoute
  AuthenticatedPlaybooksPodcastCalculatorRoute: typeof AuthenticatedPlaybooksPodcastCalculatorRoute
  AuthenticatedPlaybooksPodcastProspectingRoute: typeof AuthenticatedPlaybooksPodcastProspectingRoute
  AuthenticatedPlaybooksRevenueEngineRoute: typeof AuthenticatedPlaybooksRevenueEngineRoute
  AuthenticatedPlaybooksSmbCalculatorRoute: typeof AuthenticatedPlaybooksSmbCalculatorRoute
  AuthenticatedPlaybooksIndexRoute: typeof AuthenticatedPlaybooksIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBpsRoute: AuthenticatedBpsRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedChoosePathRoute: AuthenticatedChoosePathRoute,
  AuthenticatedCouncilEscalationsRoute: AuthenticatedCouncilEscalationsRoute,
  AuthenticatedCouncilMentorshipRoute: AuthenticatedCouncilMentorshipRoute,
  AuthenticatedCouncilPaymentsRoute: AuthenticatedCouncilPaymentsRoute,
  AuthenticatedCouncilReportsRoute: AuthenticatedCouncilReportsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDfyRoute: AuthenticatedDfyRoute,
  AuthenticatedMentorshipRoute: AuthenticatedMentorshipRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReportRoute: AuthenticatedReportRoute,
  AuthenticatedTpeRoute: AuthenticatedTpeRoute,
  AuthenticatedWeeklyReportRoute: AuthenticatedWeeklyReportRoute,
  AuthenticatedPlaybooksAscentCalculatorRoute:
    AuthenticatedPlaybooksAscentCalculatorRoute,
  AuthenticatedPlaybooksAscentMachineRoute:
    AuthenticatedPlaybooksAscentMachineRoute,
  AuthenticatedPlaybooksAscentTargetingRoute:
    AuthenticatedPlaybooksAscentTargetingRoute,
  AuthenticatedPlaybooksAuthorityCalculatorRoute:
    AuthenticatedPlaybooksAuthorityCalculatorRoute,
  AuthenticatedPlaybooksAuthorityEngineRoute:
    AuthenticatedPlaybooksAuthorityEngineRoute,
  AuthenticatedPlaybooksAuthorityProspectingRoute:
    AuthenticatedPlaybooksAuthorityProspectingRoute,
  AuthenticatedPlaybooksBroadcastEngineRoute:
    AuthenticatedPlaybooksBroadcastEngineRoute,
  AuthenticatedPlaybooksCareBridgeRoute: AuthenticatedPlaybooksCareBridgeRoute,
  AuthenticatedPlaybooksCareCalculatorRoute:
    AuthenticatedPlaybooksCareCalculatorRoute,
  AuthenticatedPlaybooksCareProspectingRoute:
    AuthenticatedPlaybooksCareProspectingRoute,
  AuthenticatedPlaybooksEcommerceCalculatorRoute:
    AuthenticatedPlaybooksEcommerceCalculatorRoute,
  AuthenticatedPlaybooksEcommerceProspectingRoute:
    AuthenticatedPlaybooksEcommerceProspectingRoute,
  AuthenticatedPlaybooksGlobalSmbEngineRoute:
    AuthenticatedPlaybooksGlobalSmbEngineRoute,
  AuthenticatedPlaybooksMinistryCalculatorRoute:
    AuthenticatedPlaybooksMinistryCalculatorRoute,
  AuthenticatedPlaybooksMinistryProspectingRoute:
    AuthenticatedPlaybooksMinistryProspectingRoute,
  AuthenticatedPlaybooksMinistrySystemsRoute:
    AuthenticatedPlaybooksMinistrySystemsRoute,
  AuthenticatedPlaybooksPlanRoute: AuthenticatedPlaybooksPlanRoute,
  AuthenticatedPlaybooksPodcastCalculatorRoute:
    AuthenticatedPlaybooksPodcastCalculatorRoute,
  AuthenticatedPlaybooksPodcastProspectingRoute:
    AuthenticatedPlaybooksPodcastProspectingRoute,
  AuthenticatedPlaybooksRevenueEngineRoute:
    AuthenticatedPlaybooksRevenueEngineRoute,
  AuthenticatedPlaybooksSmbCalculatorRoute:
    AuthenticatedPlaybooksSmbCalculatorRoute,
  AuthenticatedPlaybooksIndexRoute: AuthenticatedPlaybooksIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
